Updates Kotlin to 1.0.4, latest Android Gradle plugin, and targets API 24
antoniolg/Bandhook-Kotlin pull request #25
Opened 2016-10-17 13:50 UTC by rafaeltoledo

2016-10-19 06:52 UTC, antoniolg commented
Sorry! I merged other PRs and this now has conflicts. Could you please resolve it? Thanks for your help.

2016-10-21 02:28 UTC, rafaeltoledo commented
Just fixed the conflicts and now, as released yesterday, this PR now targets API 25 instead of 24 :)

2016-10-21 06:40 UTC, antoniolg requested changes
Apart from that little nitpick, everything looks OK. Could you please revert to the use of `"`? Thanks, and sorry!

2016-10-21 06:40 UTC, antoniolg commented on app/build.gradle
> +        testInstrumentationRunner 'android.support.test.runner.AndroidJUnitRunner'
I don't very much like the incongruence added between `'` and `"`. We need `"` for the strings that require a variable, so why not leaving all the strings like that? Both are equivalent.

2017-07-10 10:01 UTC, antoniolg commented
This PR is obsolete, closing it.

2017-07-10 10:01 UTC, closed without merging